__tests__/http-incoming.js
lib/http-incoming.js
lib/utils.js
package.json

This add a common HttpIncoming class. In the process of making Podium http framework free its introduced a common object which is to be passed between the different parts in Podium on a incoming http request. It works as follow in ex a express.js middleware:
```js
const middleware = (req, res) => {
let incoming = new HttpIncoming(req, res, res.locals);
incoming = context.process(incoming);
incoming = proxy.process(incoming);
}
```
This is the class for this object.
NOTE I: This module is currently not the most optimal place to place such a class. Though; I would at a later point like to rename this module to `common` and have it contain all the util methods currently in this module, the HttpIncoming class and move the schemas into it so code used by mutliple modules are in one common …

Introducing HttpIncoming class

---

__tests__/http-incoming.js
lib/http-incoming.js

This appends a `toJSON()` method to the HttpIncoming constructor. This makes it possible to serialize this object without getting a circular structure which causes serializing to fail. The circular structure is caused by the values set on `.request` and `.response` and these being enumerable. That we can't change, but we do not need the values on `.request` and `.response` in the cases where this object is serialized.

Add toJSON method to HttpIncoming

---

.eslintrc
benchmark/benchmark.js
lib/http-incoming.js
package.json

`HttpIncoming` lives in hot path of every request. This PR doubles the creation performance of `HttpIncoming`.
From:
```sh
new HttpIncoming() - No params x 91,806 ops/sec ±2.48% (85 runs sampled)
new HttpIncoming() - With params x 92,816 ops/sec ±2.34% (85 runs sampled)
```
to:
```sh
new HttpIncoming() - No params x 186,691 ops/sec ±1.04% (90 runs sampled)
new HttpIncoming() - With params x 186,027 ops/sec ±1.54% (92 runs sampled)
```
There is probably more performance to press out of this but that involves taking a stab on the `original-url` module.

Improve creation performance of HttpIncoming

---

__tests__/http-incoming.js
lib/http-incoming.js

When a incoming request goes through the proxy `.process()` method it can eiter result in a request being proxied or not. If a request is not proxied we continue the incoming request so one can write something as a response to the request. We do this continue process by passing on the `HttpIncoming` object.
Though; if the incoming request does yeld that it should be proxied we stopp the incoming request and write the response inside the proxy `.process()` method. In this case we do currently just [resolve without passing on anything](https://github.com/podium-lib/proxy/blob/master/lib/proxy.js#L236).
This makes cheking for this in middleware a bit non intuitive since we just [check if we got a value or not](https://github.com/podium-lib/layout/blob/master/lib/layout.js#L141).
This PR ads …

Added proxy property on HttpIncoming

---

__tests__/http-incoming.js
lib/http-incoming.js

The manifest does now hold css and js as Arrays. This should be reflected in `HttIncoming`.

Make .css and .js into Arrays

---

__tests__/__snapshots__/html-document.js.snap
__tests__/html-document.js
__tests__/utils.js
lib/html-document.js
lib/utils.js

Pull document template into a separate file (easier to link to to show as example) and make the printing of the script tags care about `type` being set to `module` or not.

Make default document template care about script type

---

__tests__/html-document.js
__tests__/http-incoming.js
lib/html-document.js
lib/http-incoming.js

Based on offline discussions the document template is now refactored to take `HttpIncoming` as the first argument.
This lifts the logic of doing the rendering of the document template to the `Podium` and `Layout` classes instead of something which is contian in `HttpIncoming`. There for `.render()` is now removed from `HttpIncoming`.
`.view` have also changed character from being a placeholder of the document template to being a object which can hold metadata to the document template.

Refactor the document template

---

__tests__/__snapshots__/html-document.js.snap
__tests__/html-document.js
lib/html-document.js

Make the default document template print `<script type="module" ....>` when a js file is defined as `esm` in the manifest.

Print module as script type for esm types

---

__tests__/asset-css.js
__tests__/asset-js.js
__tests__/http-incoming.js
lib/asset-css.js
lib/asset-js.js
lib/html-document.js
lib/utils.js
package.json

This adds a CSS and JS class which reflects the different attributes the respective `<script>` and `<link>` tags can have to load each type of asset. 
The intention of these classes are for internal use when one set CSS or JS assets through the `.css()` and `.js()` methods in @podium/podlet or @podium/layout. These classes makes it easier for us to exchange info about assets between a podlet and a layout making sure that when one use an property on the asset objects (ex in the document template) the property will always be present mo matter what the manifest contained in the exchange between a podlet and a layout.
These classes also simplifies the process of maintaining when `pathname` should be added and not to the `value` in both @podium/podlet or @podium/layout.

Add CSS and JS asset classes

---

lib/main.js
lib/utils.js
package.json

That `asset-css` and `asset-js` is exported in `utils` while being imported in `utils` created a circular dependency when this module is depended on. Prevent this.

Prevent circular dependencies

---

__tests__/asset-css.js
lib/asset-css.js

Turns out `type` for CSS is needed after all so adding type as a property to the CSS class.

Add type to CSS class

---

README.md
__tests__/__snapshots__/html-document.js.snap
__tests__/html-document.js
__tests__/html-utils.js
lib/asset-css.js
lib/asset-js.js
lib/html-document.js
lib/html-utils.js
lib/main.js
package.json

This moves the methods for building html `<script>` and `<link>` elements out of the AssetCss and AssetJs classes introduced earlier. There methods are more or less extracted out of the AssetCss and AssetJs classes and made available as public methods so its easier for custom document-templates to use these.
The default document-template shipped with podium is now using these methods to build html `<script>` and `<link>` elements.

Html utils

---

__tests__/http-incoming.js
lib/http-incoming.js

This adds a `.podlets` property to `HttpIncoming` which accept an array of client responses and join the values for `.css` and `.js` on these responses into the `.css` and `.js` properties of `HttpIncoming`.
This is better explained with an example.
This is a bit simplified but when we are doing something like this in a Layout:
```js
layout.css({ value: 'layout.css' });
layout.js({ value: 'layout.js' });
[ ... ]
const incoming = res.locals.podium;
const podlets = await Promise.all([
header.fetch(incoming),
auth.fetch(incoming),
geo.fetch(incoming),
images.fetch(incoming),
footer.fetch(incoming),
]);
```
the constant named `incoming` is an Object which holds the values set by `layout.css()` and `layout.js()` like so:
```js
{
css: [ 'layout.css' ],
js: [ 'layout.js' ],
}
```
and then the …

Added .podlets property to HttpIncoming

---

__tests__/asset-js.js
__tests__/html-utils.js
lib/asset-js.js
lib/html-utils.js

Both of the following are valid:
```js
<script src="/foo" crossorigin></script>
<script src="/foo" crossorigin=""></script>
```
However, it was not possible to set an empty string or indicate that the boolean form should be used. 
This PR makes it possible to set boolean true/false or a string as in:
```js
new AssetJs({ crossorigin: true });
new AssetJs({ crossorigin: false });
new AssetJs({ crossorigin: '' });
new AssetJs({ crossorigin: 'anonymous' });
```

support setting crossorigin to false, true and empty string

---

lib/http-incoming.js
package.json

This parses out the protocol based on the `forwarded` header. We're ignoring the rest of the header as is. This is a temporary fix related to that we lost protocol in the context.

Parse out protocol

---

__tests__/http-incoming.js
lib/http-incoming.js
package.json

In Express `request.url` is always `/`. This differ from how its in core node.js. To get the pathname of a URL in Express one need to use `request.originalUrl` instead. This PR caters for that.

Support original url

---

__tests__/asset-js.js
__tests__/html-utils.js
lib/asset-js.js
lib/html-utils.js

Hi, we are trying to use Podium together with a "part" system. We have an Express server that loads React components dynamically , and render them server side. And then we want to serve the parts as Podlets.
But when we hydrate the components on the clientside, we need to know which hydration code that is for that specific component. And what we have done is that we id the scripts with a data attribute tag, and then we mark the props inline with the id from the script.
So we need to be able to add a data attribute to the script tags :-)
Please let me know if there is another way I could achieve this.
Thank you for your help, and for a cool tool!

feat: support for data attributes on script tags

---

__tests__/asset-js.js
__tests__/html-utils.js
lib/asset-js.js
lib/html-utils.js

In #58 data attributes was introduced as a property one can set for a javascript resoirce. In the original PR this sets the data attributes as an object in the manifest like so:
```js
js : {
data_1: 'foo',
data_2: 'bar'
}
```
This is not super optimal when parsing or creating the manifest from other languages than javascript. This PR changes this behaviour to be an Array of objects with key / value properties:
```js
js :[
{ key: 'data_1', value: 'foo' },
{ key: 'data_2', value: 'bar' },
]
```
This will btw be smoothed over in the @podium/podlet API so one can set an object instead of an array objects:
```js
podlet.js({
type: 'module',
value: '/some.js',
data: {
data_1: 'foo',
data_2: 'bar'
}
})
```

fix: make 'data' property into an Array of key value objects

---

__tests__/asset-js.js
__tests__/html-utils.js
lib/asset-js.js
lib/html-utils.js

This makes it possible to set data attributes on javascript assets. Iow; the manifest will contain a new `data` property which takes an array of key / value objects like so:
```js
{
value: '/foo.js',
data: [{ 
key: 'foo',
value: 'bar'     
}],
}
```
This can then be used to build data attributes on the script tags in the html template:
```html
<script src="/foo.js" data-foo="bar"></script>
```

feat: support data attributes on javascript assets

---

index.d.ts

Forgot to add a type definition for the data attribute on the AssetJS in the [#58 ](https://github.com/podium-lib/utils/pull/58)
Now Typescript will not complain on this:
```typescript
podlet.js({
value: '/foo.js',
data: { foo: 'bar' }
})
```
Which will end up as a script element like this:
```html
<script src="/foo.js" data-foo="bar"></script>
```

fix: Added type definition for the data attribute for AssetJS.

---

__tests__/asset-css.js
__tests__/asset-js.js
lib/asset-css.js
lib/asset-js.js
package.json

It does not really make any sense using the json schema to validate the `value` argument of a JS and CSS object. The schema is intended to validate the whole object and not just one single value. Due to this the validation of the `value` argument of a JS and CSS object is simplified.
The schema is updated to use version 5.0.0-next.1 and tests to validate a JS and CSS object with the schema is added.

fix: Simplify js and css value validation

---

.eslintrc
lib/asset-css.js
lib/asset-js.js
lib/http-incoming.js
package.json

BREAKING CHANGE: Due to dropping node 10.x support we use ES private properties instead of Symbols.
We've been using Symbols to define private properties in classes up
until now. This has the downside that they are not true private and in
later versions of node.js one would see these Symbols when inspecting
an object. What we want is proper private properties.
This PR does also add a pretty printer which outputs an object literal
or the object so when debugging one can see the getters and setters
of the object.
Example: printing a object with `console.log()` would previously print
the following:
```sh
PodiumHttpIncoming {
[Symbol(podium:httpincoming:development)]: false,
[Symbol(podium:httpincoming:response)]: {},
[Symbol(podium:httpincoming:request)]: {}, …
```

feat: Use ES private properties instead of Symbols for privacy

---

__tests__/asset-css.js
__tests__/asset-js.js
__tests__/html-utils.js
lib/asset-css.js
lib/asset-js.js
lib/html-utils.js

This PR breaks the internals of building html script and link tags apart such that it was possible to then add a .toReactAttrs() method to both AssetJs and AssetCss without breaking any external facing APIs. 
This method on both the AssetCss and AssetJs classes returns an object with keys and values that work with JSX script and link tags.
This makes it possible to get back AssetJs and AssetCss instances from a Podium fetch and then easily use them in a React app like so:
```js
const { js, css, content } = await podlet.fetch(...);
```
```jsx
<script {...js.toReactAttrs()}></script>
<link {...css.toReactAttrs()} />
```

Add react support to assets

---

benchmark/benchmark.js
lib/http-incoming.js
package.json
tests/http-incoming.js

This remove the [original-url](https://www.npmjs.com/package/original-url) from `http-incoming`. We've been using this module to do out own parsing to find the original URL of a request but this is in reality double work. This is also handled by all http frameworks so we should instead set the original URL on `http-incoming` each framework provide instead of doing this parsing our self.
The [original-url](https://www.npmjs.com/package/original-url) seems to [not be very maintained](https://github.com/watson/original-url/pull/10) and is causing some deprecation warnings in ex Fastify: https://github.com/podium-lib/issues/issues/52.

fix: Remove original-url module

---

index.d.ts

The way these assets are defined today, in typescript what you "see" is e.g.
```
{
as: {as: string}
...
}
```
This is obviously incorrect. This is because of how Pick works.
This https://github.com/podium-lib/utils/pull/153 may also be correct. Just haven't verified.

fix: correct typescript definitions for assets

---

index.d.ts

Adds `toJSON` and `toJsxAttributes` to `AssetJs` and `AssetCss`

fix: add missing functions to type definition

---

.github/workflows/publish.yml
.github/workflows/test.yml
__tests__/__snapshots__/html-document.js.snap
__tests__/asset-css.js
__tests__/asset-js.js
__tests__/html-document.js
index.d.ts
lib/asset-css.js
lib/asset-js.js
lib/html-document.js
package.json

This is part of an effort to add strategy and scope fields to Podium JS/CSS assets
See https://github.com/podium-lib/schemas/pull/201
TODO
* Merge https://github.com/podium-lib/schemas/pull/201 and update utils before merging

feat: add strategy and scope fields to AssetCss and AssetJs classes

---

__tests__/asset-js.js
__tests__/html-utils.js
lib/html-utils.js

Uses dynamic imports to inside script tags for script assets that have the lazy load strategy.
Auto detects the strategy property on the asset when calling toHTML
```js
script.toHTML()
```
Which produces a script tag that looks like:
```html
<script type="module">import("/path/to/file.js");</script>
```

fix: correctly build lazy load script tag html when asset strategy is lazy

---

lib/asset-js.js
tests/asset-js.js
tests/html-utils.js

This leads to unexpected results. An option is to ignore `async` silently if passing `defer: true`, since this could start breaking things.

fix: validate inputs when passing both async and defer

---

lib/html-document.js
tests/html-document.js

This template is probably not often used, certainly not in NMP which is why we've probably never noticed that the lang 
attribute wasn't actually working in podlets.
This PR also introduces a priority order for determining lang from locale:
* incoming.view is at the app level and takes highest priority, if an app sets this directly, thats the value.
* incoming.context is used for values synced between the layout and the podlet. Due to differences between layouts and podlets, we have to check both incoming.context['podium-locale'] for layouts and incoming.context.locale for podlets.
* fallback to incoming.params which is set in Podium layout and podlet middleware/plugins. I see this as a value that can be used by other middleware or abstractions to set values that the html-template can …

fix: ensure html-template lang attribute works in both layout and podlet

---

package.json

It's not being included even with `"types"` set to what it is on L31

fix: include the types folder in the distributed package

---

lib/http-incoming.js
tests/http-incoming.test.js

Disappeared in the JSDoc rewrite (#233)

fix: add back generics to httpincoming

---

lib/asset-css.js
lib/asset-js.js
tests/asset-css.test.js
tests/asset-js.test.js

Adds toHeader methods to both AssetCss and AssetJs.
Couple thoughts.
1. Early hints are typically used to produce preload Link headers so perhaps .toHeader would actually be a better name since thats what's happening here. (done, renamed to toHeader)
2. While the strings being produced are (I believe) strictly valid for sending as Link headers, they are highly non standard since we send all kinds of properties that the browser isn't going to do anything with. I think this is necessary since we want to basically use the Link header string as a full serialisation of the AssetJs or AssetCss object so it can be sent to the layout. Anything less would make many of the asset properties useless as they would never make it to the layout. See diagram below for how I think this all fits together. …

feat: add toHeader methods to Asset classes

---

lib/asset-css.js
lib/asset-js.js
tests/asset-css.test.js
tests/asset-js.test.js

In order to avoid trying to detect what sort of asset is being sent (using file extensions), its best that we explicitly send this information from the podlet to the layout since we have it.

feat: add asset-type link header attribute and set to either style or script

---

lib/asset-css.js
lib/asset-js.js
tests/asset-css.test.js
tests/asset-js.test.js

Moving this tag handling to the podlet and the layout so that toHeader is still useful in situations where the asset-type tagging is not needed. Eg. from the client to the browser when generating preload headers.

fix: remove asset type header tagging

---

lib/hints.js
lib/http-incoming.js
package.json
tests/asset-css.test.js
tests/asset-js.test.js
tests/hints.test.js
tests/http-incoming.test.js

this PR adds a new hints property to HttpIncoming that can be used in the Podium client to track early hints as requests are sent and early hints are received back.
Eg. 
```js
...
incoming.hints.on('complete', () => {
// all early hints have been received!
});
...
fetch(incoming, ...) {
incoming.hints.addExpectedHint(this.name);
// do the request
request({
onInfo() {
incoming.hints.addReceivedHint(this.name);
}
});
}
```

Add hints support to incoming
